// Curated list of Vietnamese universities (commonly known)
export const VN_UNIVERSITIES = [
  'Đại học Bách khoa Hà Nội',
  'Đại học Quốc gia Hà Nội',
  'Đại học Quốc gia TP. Hồ Chí Minh',
  'Đại học Bách khoa - ĐHQG TP.HCM',
  'Đại học Khoa học Tự nhiên - ĐHQG Hà Nội',
  'Đại học Khoa học Tự nhiên - ĐHQG TP.HCM',
  'Đại học Khoa học Xã hội và Nhân văn - ĐHQG Hà Nội',
  'Đại học Khoa học Xã hội và Nhân văn - ĐHQG TP.HCM',
  'Đại học Kinh tế Quốc dân',
  'Đại học Kinh tế TP. Hồ Chí Minh',
  'Đại học Ngoại thương',
  'Đại học Ngoại thương - Cơ sở 2 TP.HCM',
  'Đại học Thương mại',
  'Đại học Hà Nội',
  'Đại học Sư phạm Hà Nội',
  'Đại học Sư phạm TP. Hồ Chí Minh',
  'Đại học Y Hà Nội',
  'Đại học Y Dược TP. Hồ Chí Minh',
  'Đại học Dược Hà Nội',
  'Đại học Luật Hà Nội',
  'Đại học Luật TP. Hồ Chí Minh',
  'Đại học Xây dựng Hà Nội',
  'Đại học Giao thông Vận tải',
  'Đại học Giao thông Vận tải TP.HCM',
  'Đại học Mỏ - Địa chất',
  'Đại học Thủy lợi',
  'Đại học Nông nghiệp Việt Nam',
  'Học viện Tài chính',
  'Học viện Ngân hàng',
  'Học viện Báo chí và Tuyên truyền',
  'Học viện Bưu chính Viễn thông',
  'Học viện Công nghệ Bưu chính Viễn thông',
  'Học viện Ngoại giao',
  'Học viện Hành chính Quốc gia',
  'Học viện Quân y',
  'Học viện An ninh Nhân dân',
  'Học viện Cảnh sát Nhân dân',
  'Đại học FPT',
  'Đại học FPT Hà Nội',
  'Đại học FPT TP. Hồ Chí Minh',
  'Đại học FPT Đà Nẵng',
  'Đại học FPT Cần Thơ',
  'Đại học FPT Quy Nhơn',
  'Đại học RMIT Việt Nam',
  'Đại học Quốc tế - ĐHQG TP.HCM',
  'Đại học VinUniversity',
  'Đại học Tôn Đức Thắng',
  'Đại học Hoa Sen',
  'Đại học Văn Lang',
  'Đại học Duy Tân',
  'Đại học Nguyễn Tất Thành',
  'Đại học Công nghiệp TP. Hồ Chí Minh',
  'Đại học Công nghiệp Hà Nội',
  'Đại học Công nghệ - ĐHQG Hà Nội',
  'Đại học Công nghệ TP. Hồ Chí Minh (HUTECH)',
  'Đại học Công nghệ Thông tin - ĐHQG TP.HCM',
  'Đại học Sư phạm Kỹ thuật TP. Hồ Chí Minh',
  'Đại học Sư phạm Kỹ thuật Hưng Yên',
  'Đại học Kiến trúc Hà Nội',
  'Đại học Kiến trúc TP. Hồ Chí Minh',
  'Đại học Mỹ thuật Việt Nam',
  'Đại học Mỹ thuật Công nghiệp',
  'Đại học Sân khấu - Điện ảnh Hà Nội',
  'Đại học Văn hóa Hà Nội',
  'Đại học Đà Nẵng',
  'Đại học Bách khoa - Đại học Đà Nẵng',
  'Đại học Kinh tế - Đại học Đà Nẵng',
  'Đại học Sư phạm - Đại học Đà Nẵng',
  'Đại học Huế',
  'Đại học Y Dược Huế',
  'Đại học Cần Thơ',
  'Đại học Nha Trang',
  'Đại học Đà Lạt',
  'Đại học Quy Nhơn',
  'Đại học Vinh',
  'Đại học Thái Nguyên',
  'Đại học Hải Phòng',
  'Đại học Hùng Vương',
  'Đại học Tây Nguyên',
  'Đại học An Giang',
  'Đại học Trà Vinh',
  'Đại học Tiền Giang',
  'Đại học Đồng Tháp',
  'Đại học Sài Gòn',
  'Đại học Mở TP. Hồ Chí Minh',
  'Đại học Mở Hà Nội',
  'Đại học Tài chính - Marketing',
  'Đại học Ngân hàng TP. Hồ Chí Minh',
  'Đại học Ngoại ngữ - ĐHQG Hà Nội',
  'Đại học Ngoại ngữ - Đại học Đà Nẵng',
  'Đại học Ngoại ngữ - Đại học Huế',
  'Đại học Lao động - Xã hội',
  'Đại học Điện lực',
  'Đại học Tài nguyên và Môi trường Hà Nội',
  'Đại học Lâm nghiệp Việt Nam',
  'Đại học Thể dục Thể thao Bắc Ninh',
  'Đại học British University Vietnam',
  'Đại học Fulbright Việt Nam',
];
